export const CONFIG = {
  GAME_WIDTH: 800,
  GAME_HEIGHT: 600,
  HUD_HEIGHT: 40,

  PADDLE_WIDTH: 120,
  PADDLE_HEIGHT: 16,
  PADDLE_SPEED: 400,

  BALL_SIZE: 14,
  BALL_SPEED: 350,

  BRICK_ROWS: 5,
  BRICK_COLS: 8,
  BRICK_WIDTH: 80,
  BRICK_HEIGHT: 24,
  BRICK_PADDING: 8,
  BRICK_OFFSET_TOP: 60,
  BRICK_OFFSET_LEFT: 20,

  INITIAL_LIVES: 3,
}
